version: '3.8'

services:
  db:
    image: mariadb:10.4.32
    container_name: botica-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: boticaintegrador2
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: botica-phpmyadmin
    restart: always
    ports:
      - "8081:80"  # ← CAMBIÉ ESTO: 8081 en lugar de 8080
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  mariadb_data:

#docker-compose down
#docker-compose up -d