spring.application.name=boticaIntegrador
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/boticaintegrador2
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Esto actualizará las tablas automáticamente desde tus entidades JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false