spring.application.name=boticaIntegrador
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/boticaintegrador2
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

# src/main/resources/application.properties
twilio.account.sid=AC6168196d54ef765f6864ac1b68e9586c
twilio.auth.token=b8d2d53b6ee1ca7cf14d864b480c783a
twilio.phone.number=+18172420459